"""
    Credits to : Tiagosf00
    https://github.com/Tiagosf00/Competitive-Programming
"""
import os
import subprocess
import shutil
import argparse
from pathlib import Path

# TODO: fix path code duplicated

# Get the path from the command line
parser = argparse.ArgumentParser(description="Create notebook from C++ files.")
parser.add_argument(
    "--path", type=str, default="C++", help="Path to implementation paths"
)
args = parser.parse_args()
path = args.path


def cpy_template():
    # gets the path from the file gen.py
    path = Path(__file__).parent.absolute()
    template = path / "template.tex"
    notebook = path / "notebook.tex"
    shutil.copyfile(template, notebook)


def remove_aux():
    """Remove the auxiliar files generated by pdflatex"""
    to_remove = [
        "notebook.aux",
        "notebook.log",
        "notebook.toc",
        "notebook.tex",
        "texput.log",
    ]
    for item in to_remove:
        if os.path.exists(item):
            os.remove(item)


ignore_dir = ["ds-c"]


def get_dir():
    section_list = os.listdir(path)
    section = []
    for section_name in section_list:
        if (
            not os.path.isdir(os.path.join(path, section_name))
            or section_name in ignore_dir
        ):
            continue
        print(section_name)
        subsection = []
        section_path = os.path.join(path, section_name)
        items = os.listdir(section_path)
        for file_name in items:
            print(file_name)
            if file_name.endswith(".cpp") or file_name.endswith(".py"):
                subsection.append(file_name)
            elif os.path.isdir(os.path.join(section_path, file_name)):
                # Sub Directory
                sub_files = os.listdir(os.path.join(section_path, file_name))
                subsection.extend(
                    [
                        os.path.join(file_name, name)
                        for name in sub_files
                        if name.endswith(".cpp")
                    ]
                )

        section.append((section_name, subsection))
    return section


def create_notebook(section):
    aux = ""
    print("Generating notebook...")
    with open(Path(__file__).parent.absolute() / "notebook.tex", "a") as texfile:
        for item, subsection in section:
            print("item: ", item, " subsection: ", subsection, flush=True)
            aux += f"\\section{{{item.replace('-', ' ')}}}\n"
            for file in subsection:
                name, _ = os.path.splitext(file)
                name = os.path.split(name)[1]  # Remove Segtree/ prefix
                file_name = " ".join([x.capitalize() for x in name.split("_")])
                file_path = os.path.join(path, item, file).replace("\\", "/")

                print("file_name: ", file_name,
                      " file_path: ", file_path, flush=True)
                aux += "\\includes{%s}{%s}\n" % (file_name, file_path)

        aux += "\n\\end{multicols}\n\\end{document}\n"
        texfile.write(aux)

    print("notebook.tex created !")


def main():
    cpy_template()
    section = get_dir()
    create_notebook(section)

    script_path = Path(__file__).parent.absolute() / "notebook.tex"
    cmd = ["pdflatex", "-interaction=nonstopmode",
           "-halt-on-error", script_path]
    with open(os.devnull, "w") as DEVNULL:
        try:
            subprocess.check_call(cmd)
            subprocess.check_call(cmd)
        except Exception:
            print("Error while converting LaTex to pdf.")
            print("You can run it manually to see the error.")
            print("pdflatex -interaction=nonstopmode -halt-on-error notebook.tex")
            exit(1)

    remove_aux()

    print("Notebook successfully created !")


if __name__ == "__main__":
    main()
